services:
  - type: web
    name: backend-gym
    env: node
    plan: free
    branch: main
    rootDir: .
    buildCommand: npm install --include=dev && npx nest build
    startCommand: npm run start:prod
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_LOCAL_URI
        sync: false
      - key: MONGO_DB_NAME
        value: gymdb
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1h
