export const CLIENT_REPOSITORY = 'CLIENT_REPOSITORY';
export const LOGIN_REPOSITORY = 'LOGIN_REPOSITORY';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const TRAINER_REPOSITORY = 'TRAINER_REPOSITORY';
